version: '3.8'
services:
  banking-server:
    networks:
      - numble-banking-network
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banking-db
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: eZkRv7nG786pcyr3
      SEED_ENABLED: ${SEED_ENABLE}
  mysql:
    networks:
      - numble-banking-network
    image: mysql:8.0
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: qsWWNdb8XKN4EKRW
      MYSQL_DATABASE: banking-db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: eZkRv7nG786pcyr3
    ports:
      - "3306:3306"
  mysql-test:
    networks:
      - numble-banking-network
    image: mysql:8.0
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: qsWWNdb8XKN4EKRW
      MYSQL_DATABASE: banking-db-test
      MYSQL_USER: db_user
      MYSQL_PASSWORD: eZkRv7nG786pcyr3
    ports:
      - "25000:3306"
  redis:
    image: redis:6
    networks:
      - numble-banking-network
    ports:
      - "6379:6379"


networks:
  numble-banking-network:
    external: true
    driver: bridge