spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: db_user
    password: eZkRv7nG786pcyr3
    url: jdbc:mysql://127.0.0.1:25000/banking-db-test
  exposed:
    generate-ddl: true
  security:
    user:
      name: admin
      password: admin
jwt:
  secret: prographyabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz